Is this some kind of a cave? #color:ffffff #sound:1
There is no way to climb back up...
Maybe there will be exit further?
But...
It is so dark in there, so I can't see a thing...
Hmm... some light is coming through the rocks, what if I follow it?
