What is this place? #color:ffffff #sound:1
It looks so wierd...
But I have no other choice here...
I should go further.
Also I should take that lantern.
I definately don't want to be left alone in the darkness...