I'm so grateful that she changed it, but... #color:ffffff #sound:1
What's with the nurses here?
Maybe that is some kind of an experimant?
Or she is my secret therapist of some kind or...
I just can't think of any reasonable answer...
