I know there are a lot of people who would like to be alone in hispital wards. #color:ffffff #sound:1
But honestly...
It is quite lonely here.
And I don't even have friends that could visit me...
I hope this disease of mine ends soon.